### ISSUE TITLE
dbptk-developer custom view

### ISSUE THREAD

**Issue by mezeijozsef** [keeps/dbptk-developer#567]
Description: 
My goal would be to create SIARD using every single table inside the database and also to create a custom view. It ignores every single table then terminates.

Steps required to reproduce the bug:

1. Using command: java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.10.4.jar migrate -i import-config --import-file=config.yml --export siard-2 --export-file=example.siard

Attach the dbptk-app.log.txt file below.

[config.yml.txt](https://github.com/keeps/dbptk-developer/files/13492574/config.yml.txt) _remove .txt_
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/13492582/dbptk-app.log.txt)

I would like to ask for help because I might overlook something.

**Comment by hmiguim** [comment]
Hi,

```yml
schemas:
  sakila:
    custom:
      - name: "EGYEDI_NEZET"
        description: "Ez a nézet értelmezhetően és összeszedetten tartalmazza az adatcsomagban található információkat."
        query: "select * from BK01"
    tables:
    - name: "BK01"
      columns:
      - name: "B1"
      - name: "BKA"
      - name: "BKC"
      - name: "BKD"
      where: ""
      orderBy: ""
```

The schema you are trying to connect is the sakila?
